services:
  - type: web
    name: pneumonia-prediction
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    pythonVersion: "3.10.13"
